import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navigation } from './resources/components';
import axios from 'axios';
import { config } from 'process';
import { configVariable } from './resources/constant/ConfigVariable';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

axios.create({baseURL:configVariable.BASE_URL});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' bg-slate-200'>
      <body className={inter.className}>
        <Navigation/>
        {children}
        </body>
    </html>
  )
}
